# -*- coding: utf-8 -*-
"""Ingredients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp-wqm0WhisjpuiG2i_VpaGNppPIIsN-
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_recipe(shopping_list):
    # Create prompt for Flan-T5
    prompt = f"Suggest 3 recipes using these ingredients: {shopping_list}"

    # Tokenize input
    inputs = tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)

    # Generate recipes
    outputs = model.generate(
        **inputs,
        max_length=500,
        num_beams=5,
        no_repeat_ngram_size=2,
        early_stopping=True
    )

    # Decode output
    recipes = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return recipes

shopping_list =  "Last weekend, I went grocery shopping to prepare for a small family dinner. I picked up some bread and butter for breakfast, along with a carton of milk for tea and desserts. Since my sister loves sweets, I also grabbed a jar of honey to drizzle over pancakes. Later, I thought of making a light dinner, so I added chicken, tomatoes, and some fresh spinach to the basket. To spice things up, I couldn’t resist buying a packet of chili powder and a bunch of fresh coriander leaves."

print("Generated Recipes:\n", generate_recipe(shopping_list))